config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'tops#index'
  resources :rooms, only: [:new, :create, :destroy] do
    resources :messages, only: [:index, :create]
  end
  resources :users, only: [:edit, :update, :show]
  devise_scope :users do
    get '/users', to: redirect("/users/sign_up")
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord

  validates :content, presence: true

  belongs_to :room
  belongs_to :user

end

app/models/room.rb
class Room < ApplicationRecord

  validates :title, presence: true
  
  belongs_to :user
  has_many :room_tags ,dependent: :destroy
  has_many :tags ,through: :room_tags
  has_many :messages,dependent: :destroy

  def save_tags(sent_tags)
    current_tags = self.tags.pluck(:name) unless self.tags.nil?

    old_tags = current_tags - sent_tags
    fresh_tags = sent_tags - current_tags

    old_tags.each do |old|
      self.tag.deleteTag.find_by(name: old)
    end

    fresh_tags.each do | fresh|
      fresh_room_tags = Tag.find_or_create_by(name: fresh)
      self.tags <<  fresh_room_tags
    end
  end
end

app/models/room_tag.rb
class RoomTag < ApplicationRecord
  belongs_to :room
  belongs_to :tag
  
  validates :room_id, presence: true
  validates :tag_id, presence: true
end

app/models/school_year.rb
class SchoolYear < ActiveHash::Base
  self.data = [
    { id: 1, year: '---' },
    { id: 2, year: '中学１年生' },
    { id: 3, year: '中学２年生' },
    { id: 4, year: '中学３年生' },
    { id: 5, year: '高校１年生' },
    { id: 6, year: '高校２年生' },
    { id: 7, year: '高校３年生' }
  ]

  include ActiveHash::Associations
  has_many :users
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :room_tags,dependent: :destroy
  has_many :rooms,through: :room_tags

  validates :name, uniqueness: { case_sensitive: true }, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
   validates :name
   validates :school_year_id, numericality: { other_than: 1, message: "can't be blank" }
  end
  has_many :rooms
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :school_year_id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :instance_variable, only: [:index, :create]
  def index
    @tags = Tag.all
  end

  def create
    message = @room.messages.new(message_params)
    if message.save
      redirect_to room_messages_path(@room)
    else
      
      render :index
    end
  end

  private

  def instance_variable
    @message = Message.new
    @room = Room.find(params[:room_id])
    @room_tags = @room.tags
    @messages = @room.messages.includes(:user)
  end
  
  def message_params
    params.require(:message).permit(:content).merge(user_id: current_user.id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  before_action :only_user, only: :destroy
  def new
    @room = Room.new
    @tags = Tag.all
  end
  def create
    @room = Room.new(room_params)
    tag_list = params[:room][:name].split(',')
    if @room.save
      @room.save_tags(tag_list)
      redirect_to root_path
    else
      @room = Room.new
      render :new
    end
  end
  def destroy
    @room.destroy
    redirect_to user_path(current_user.id)
  end

  private

  def room_params
    params.require(:room).permit(:title).merge(user_id: current_user.id)
  end

  def only_user
    @room = Room.find(params[:id])
    redirect_to root_path unless current_user.id == @room.user_id
  end
  
  
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
    @rooms = Room.includes(:user)
    @tags = Tag.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_find, only: [:edit, :update, :show]
  before_action :user_only, only: [:update, :edit]

  def show
    @school_year = SchoolYear.find(@user.school_year_id)
    @tags = Tag.all
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_find
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :school_year_id)
  end

  def user_only
    redirect_to root_path unless current_user.id == @user.id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudyRoom</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap');
    </style>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/index.html.erb
<%=render 'shared/header' %>
<div class="message-top">
  <div class="message-main">
    <div class="message-up">
      <div class="room-message-title">
        <%= @room.title %>
      </div>
      <div class="room-message-tag">
        <% @room_tags.each do |tag| %>
          #<%= tag.name %>
        <% end %>
      </div>
    </div>
    <div class="messages-index">

      <% @messages.each do |message| %>
        <div class="message">
          <div class="message-text-up">
            <div class="message-user-name"><%= message.user.name %></div>
            <div class="message-time"><%= l message.created_at %></div>
          </div>
          <div class="message-content"><%= message.content %></div>
        </div>
      <% end %>

    </div>
    <% if user_signed_in? %>
      <div class="message-form">
        <%= form_with model: [@room, @message], local: true do |f| %>
          <%= f.text_field :content, class: 'form-content' %>
          <%= f.submit :送信, class: 'form-submit' %>
        <% end %>
      </div>
    <% end %>
  </div>
  <%= render 'shared/side_bar' %>
</div>

app/views/rooms/new.html.erb
<%= render 'shared/header' %>
<div class='room-new'>
  <div class='room-new-main'>
    <div class='room-form'>
      <h1>新規ルーム作成</h1>
      <%=form_with model: @room, local: true do |f|%>
        <%= render 'devise/shared/error_messages', model: f.object %>
        <div class='room-form-field'>
          <div class='room-form-field-left'>
            <%= f.label :title, :ルーム名, class: 'room-form-label', for: 'room-name' %>
          </div>
          <div class='room-form-field-right'>
            <%= f.text_field :title, class: 'room-form-input', placeholder: 'ルーム名を入力してください', id: 'room-name' %>
          </div>
        </div>
        <div class='room-form-field'>
          <div class='room-form-field-left'>
            <%= f.label :name, :タグ, class: 'room-form-label', for: 'room-tag' %>
          </div>
          <div class='room-form-field-right'>
            <%= f.text_field :name, class: 'room-form-input', placeholder: 'タグを入力してください', id: 'room-tag' %>
          </div>
        </div>
        <div class='room-form-submit'>
          <%= f.submit 'ルームを作成する', class: 'room-form-submit-btn' %>
        </div>
      <% end %>
    </div>
  </div>
  <%=render 'shared/side_bar' %>
</div>

app/views/shared/_header.html.erb
<header class='top-page-header'>
  <div class='header-title'>
    <%= link_to 'Study Room', root_path %>
  </div>
  <div class='nav'>
    <ul class='lists-right'>
    <% if user_signed_in? %>
      <li><%= link_to current_user.name, user_path(current_user), class: "user-name" %></li>
      <li><%= link_to 'ユーザー編集', edit_user_path(current_user), class: "user-edit" %></li>
      <li><%= link_to 'ルームの作成', new_room_path, class: "user-new" %></li>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
    <% else %> 
      <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
      <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
    <% end %>
    </ul>
  </div>
</header>

app/views/shared/_side_bar.html.erb
<div class="side_bar">
  <h3>タグ一覧</h3>
  <div class="tag-lists">
    <% @tags.each do |tag| %>
      <div class="tag-list">
        <a href="#">・<%= tag.name %></a>
      </div>
    <% end %>
  </div>
</div>

app/views/tops/index.html.erb
<%= render 'shared/header' %>
<div class="top-main">
  <div class="user-show">
    <div class="user-room">
      <div class="user-show-title">
        <h2>ルーム一覧</h2>
      </div>
      <div class="top-rooms">
        <% @rooms.each do |room| %>
          <div class="top-room">
            <div class="room-title"><%= link_to room.title, room_messages_path(room.id) %></div>
              <div class="room-tags">
                <% room.tags.each do |tag| %>
                 <div class="room-tag">#<%= tag.name %></div>
                <% end %>
              </div>
            <div class="room-name"><%= link_to room.user.name, user_path(room.user_id) %></div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <%= render 'shared/side_bar' %>
</div>

app/views/users/edit.html.erb
<div class='user_box'>
  <div class='user_box-inner'>
    <div class='user_box-header'>
      <h1>アカウント編集</h1>
    </div>
    <div class='user_box-main'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='login-flash-message'>
          <%= flash[:notice] %>
          <%= flash[:alert] %>
        </div>
        <div class='field'>
          <div class='field-label'>
            <label for='user-name'>名前</label>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true, id:'user-name' %>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <label>学年</label>
          </div>
          <div class='field-input'>
            <%= f.collection_select(:school_year_id, SchoolYear.all, :id, :year, {}, {class:"select-box", id:"item-sales-status"}) %>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <label>メールアドレス</label>
          </div>
          <div class='field-input'>
            <%= f.email_field :email, autofocus: true%>
          </div>
        </div>
        <div class='actions-sign-up'>
          <%= f.submit "編集確定", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= render 'shared/header' %>
<div class="user-main">
  <div class="user-show">
    <div class="user-show-up">
      <div class="user-show-title">
        <h2 >ユーザー詳細</h2>
      </div>
      <div class="user-show-contents">
        <div class="user-show-name">
          <h2><%= @user.name %></h2>
        </div>
        <div class="user-show-school_year">
          <h3><%= @school_year.year %></h3>
        </div>
      </div>
    </div>
    <div class="user-room">
      <div class="user-show-title">
        <h2>ルーム一覧</h2>
      </div>
      <div class="rooms">
        <% @user.rooms.each do |room| %>
          <div class="room">
            <div class="room-up">
              <div class="room-title"><%=link_to room.title, room_messages_path(room.id) %></div>
              <div class="room-delete"><%= link_to 'ルームの削除', room_path(room.id), method: :delete %></div>
            </div>
            <div class="room-tags">
              <% room.tags.each do |tag| %>
               <div class="room-tag">#<%= tag.name %></div>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <%= render 'shared/side_bar' %>
</div>